name: Reusable - Build de imagenes Docker

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string

jobs:
  build_images:
    name: "${{ matrix.service.name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: Catalog
            path: src/catalog
          - name: Orders
            path: src/orders
          - name: Checkout
            path: src/checkout
          - name: UI
            path: src/ui
          - name: Admin
            path: src/admin
          - name: Cart
            path: src/cart
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build \
            --tag retail-${{ matrix.service.name }}:${{ inputs.image-tag }} \
            ${{ matrix.service.path }}
