name: Reusable - Publicacion de imagenes de contenedor

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      ecr-repository-prefix:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false

jobs:
  publish_images:
    name: Publicacion imagen Docker - ${{ matrix.service.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: catalog
            path: src/catalog
          - name: orders
            path: src/orders
          - name: checkout
            path: src/checkout
          - name: ui
            path: src/ui
          - name: admin
            path: src/admin
          - name: cart
            path: src/cart
    env:
      AWS_REGION: ${{ inputs.aws-region }}
      ECR_REPOSITORY_PREFIX: ${{ inputs.ecr-repository-prefix }}
      IMAGE_TAG: ${{ inputs.image-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login a Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build
        id: image
        run: |
          image_uri="${{ steps.ecr.outputs.registry }}/${ECR_REPOSITORY_PREFIX}/${{ matrix.service.name }}:${IMAGE_TAG}"
          echo "uri=${image_uri}" >> "$GITHUB_OUTPUT"
          docker build --tag "$image_uri" ${{ matrix.service.path }}

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: "${{ steps.image.outputs.uri }}"
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Push a ECR
        run: |
          docker push "${{ steps.image.outputs.uri }}"
